imports:
- path: https://raw.githubusercontent.com/40net-cloud/fortinet-gcp-solutions/master/gcp-dm/hub/fortigate-security-hub.jinja
  name: fortigate-security-hub.jinja
- path: https://raw.githubusercontent.com/40net-cloud/fortinet-gcp-solutions/master/gcp-dm/fortigate/ha-ap.jinja
  name: ha-ap.jinja

resources:
- name: SecurityHub
  type: fortigate-security-hub.jinja
  properties:
    region: europe-west1
    zones:
    - europe-west1-d
    - europe-west1-c
