imports:
- path: fortigate-security-hub.jinja
- path: ../fortigate/ha-ap-elb.jinja
  name: ha-ap.jinja
- path: ../license1.lic
  name: license1.lic
- path: ../license2.lic
  name: license2.lic

resources:
- name: SecurityHub
  type: fortigate-security-hub.jinja
  properties:
    region: europe-west1
    zone1: europe-west1-d
    zone2: europe-west1-c
    fgtInstanceType: e2-highcpu-4
    version: 6.4.0
    license:
      type: byol
      lic1: license1.lic
      lic2: license2.lic
    spokeNetworks:
    - name: one
      ipCidrRange: 192.168.1.0/24
    - name: two
      ipCidrRange: 192.168.2.0/24
    - name: three
      ipCidrRange: 192.168.3.0/24
    publicIPs:
    - name: app1
    - name: app2

outputs:
  - name: Management_IP
    value: $(ref.SecurityHub.Management_IP)
  - name: Default_Password
    value: $(ref.SecurityHub.Default_Password)
