imports:
- path: fortigate-security-hub.jinja
- path: ../fortigate/ha-ap-elb.jinja
  name: fortigate.jinja
- path: ../secrets/license1.lic
  name: license1.lic
- path: ../secrets/license2.lic
  name: license2.lic

resources:
- name: SecurityHub
  type: fortigate-security-hub.jinja
  properties:
    region: europe-west1
    zones:
    - europe-west1-d
    - europe-west1-c
    fgtInstanceType: e2-highcpu-4
    version: 6.2.3
    license:
      type: byol
      lics:
      - license1.lic
      - license2.lic
    spokeNetworks:
    - name: one
      ipCidrRange: 192.168.1.0/24
    - name: two
      ipCidrRange: 192.168.2.0/24
    - name: three
      ipCidrRange: 192.168.3.0/24
    publicIPs:
    - name: app1
    - name: app2

outputs:
  - name: Management_IP
    value: $(ref.SecurityHub.Management_IP)
  - name: Default_Password
    value: $(ref.SecurityHub.Default_Password)
