imports:
- path: ../../../modules-dm/singlevm2.jinja
  name: singlevm2.jinja
- path: ../../../modules-dm/utils-sample-vpcs.jinja
  name: sample-vpcs.jinja
- path: ../../../../secrets/FGVM04TM21008011.lic
  name: byol.lic

resources:
# First call the helper tempalate to create 2 VPC Networks with 2 subnets
- name: Sample_Networks
  type: sample-vpcs.jinja
  properties:
    region: europe-west1
    networks:
    - external
    - lan1
    - lan2
    - lan3
    - lan4
    - lan5
    - lan6
    - lan7

# Next, let's deploy a FortiGate instance with network interfaces in 2 VPCs we created above
- name: Fortigate
  type: singlevm2.jinja
  properties:
    zone: europe-west1-b
    instanceType: e2-standard-8
    license:
      type: byol
      lic: byol.lic
    networks:
    - name: ext
      vpcLink: $(ref.Sample_Networks.external-vpc)
      subnetLink: $(ref.Sample_Networks.external-sb)
      ipCidrRange: 172.20.0.0/24
      externalIP:
        name: ext-ip
    - name: lan1
      vpcLink: $(ref.Sample_Networks.lan1-vpc)
      subnetLink: $(ref.Sample_Networks.lan1-sb)
      ipCidrRange: 172.20.1.0/24
    - name: lan2
      vpcLink: $(ref.Sample_Networks.lan2-vpc)
      subnetLink: $(ref.Sample_Networks.lan2-sb)
      ipCidrRange: 172.20.2.0/24
    - name: lan3
      vpcLink: $(ref.Sample_Networks.lan3-vpc)
      subnetLink: $(ref.Sample_Networks.lan3-sb)
      ipCidrRange: 172.20.3.0/24
    - name: lan4
      vpcLink: $(ref.Sample_Networks.lan4-vpc)
      subnetLink: $(ref.Sample_Networks.lan4-sb)
      ipCidrRange: 172.20.4.0/24
    - name: lan5
      vpcLink: $(ref.Sample_Networks.lan5-vpc)
      subnetLink: $(ref.Sample_Networks.lan5-sb)
      ipCidrRange: 172.20.5.0/24
    - name: lan6
      vpcLink: $(ref.Sample_Networks.lan6-vpc)
      subnetLink: $(ref.Sample_Networks.lan6-sb)
      ipCidrRange: 172.20.6.0/24
    - name: lan7
      vpcLink: $(ref.Sample_Networks.lan7-vpc)
      subnetLink: $(ref.Sample_Networks.lan7-sb)
      ipCidrRange: 172.20.7.0/24

outputs:
- name: singlevm2_template
  value: $(ref.Fortigate)
