imports:
- path: https://raw.githubusercontent.com/bartekmo/forti-gcp/master/hub/fortigate-security-hub.jinja
  name: fortigate-security-hub.jinja
- path: ttps://raw.githubusercontent.com/bartekmo/forti-gcp/master/hub/utils/netcalc.jinja
  name: utils/netcalc.jinja
- path: ttps://raw.githubusercontent.com/bartekmo/forti-gcp/master/hub/utils/fgtconfig.jinja
  name: utils/fgtconfig.jinja

resources:
- name: SecurityHub
  type: fortigate-security-hub.jinja
  properties:
    region: europe-west1
    zone1: europe-west1-d
    zone2: europe-west1-c
    fgtInstanceType: e2-highcpu-4
    license: 
      type: "byol"
      lic1: license1.lic
      lic2: license2.lic
    spokeNetworks:
    - name: one
      ipCidrRange: 192.168.1.0/24
    - name: two
      ipCidrRange: 192.168.2.0/24
    - name: three
      ipCidrRange: 192.168.3.0/24
