imports:
- path: fortigate-security-hub.jinja
- path: license1.lic
- path: license2.lic
- path: utils/netcalc.jinja

resources:
- name: SecurityHub
  type: fortigate-security-hub.jinja
  properties:
    region: europe-west1
    zone1: europe-west1-d
    zone2: europe-west1-c
    fgtInstanceType: e2-highcpu-4
    license: 
      type: "byol"
      lic1: license1.lic
      lic2: license2.lic
